Added Improved QuickSort.cpp
diptangsu/Sorting-Algorithms pull request #139
Opened 2020-09-30 20:16 UTC by suraj0223

Implementation of 3 way partition Quick Sort.

2020-09-30 20:40 UTC, diptangsu commented
Just rename the file to `ThreeWayQuickSort.cpp`

2020-09-30 20:50 UTC, suraj0223 commented
@diptangsu Please Review again Updates done.

2020-10-02 18:02 UTC, diptangsu commented
Is there a reason why the partition function begins with a capital P?
Also, it would be fair to call the function `threeWayQuickSort` instead of whatever snake case naming convention you've used.

2020-10-02 18:27 UTC, suraj0223 commented
3 way partition Quick sort perform better when there is repeated element in the list as compared to 2 way partition Quick sort.
check it out here : [ 3 way sorting visualization](https://www.toptal.com/developers/sorting-algorithms)

2020-10-02 20:28 UTC, diptangsu commented on Cpp/ThreeWayQuickSort.cpp
> +pair<int,int> Partition(vector<int> &v1, int l, int r) {
refactor to `partition`

2020-10-02 20:28 UTC, diptangsu commented on Cpp/ThreeWayQuickSort.cpp
> +void randomized_quick_sort(vector<int> &v1, int l, int r) {
change all snake case function names to camelCase names

2020-10-02 20:29 UTC, diptangsu requested changes
Please make the necessary changes.

2020-10-05 06:37 UTC, diptangsu approved these changes

2020-10-05 06:37 UTC, merged